### ISSUE TITLE
Error when config not exists

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_autoit_helper#1]
First install of plugin. no config file exists.
Call "Set Autoit path":
```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/home/user/.config/cudatext/py/cuda_autoit_helper/__init__.py", line 23, in __init__
    with open(self.filesettings) as fs:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.config/cudatext/settings/cuda_autoit_helper.json'
```

**Comment by OlehL** [comment]
fix in 1217dc0
