### ISSUE TITLE
If no AutoIt dir is set- Tab key gives error

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_autoit_helper#4]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.config/cudatext/py/cuda_autoit_helper/__init__.py", line 185, in on_key
    for f in self.functions:
AttributeError: 'Command' object has no attribute 'functions'
```

**Comment by Alexey-T** [comment]
ошибка - при нажатии ТАБ на новом пустом файле на пустой строкке.

**Comment by OlehL** [comment]
fix in d6e6a05
